name: Deploy React App
on: push
jobs:
  testDep:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
