name: Deploy React App
on: push
jobs:
  testDep:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    needs: testDep
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Lint App
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Deploy
        run: echo Deploying ...
